### ISSUE TITLE
`PeekableLexer::span` changes after a peek

### ISSUE THREAD

**Issue by iamkroot** [ark0f/logos-iter#1]
Thanks for creating this crate! It has been very useful. 

I have a minor bug, best understood with an example-

```rust
let mut l = Token::lexer("1+2").peekable_lexer();
assert_eq!(l.next(), Some(Token::I32Literal(1)));
assert_eq!(l.span(), 0..1);
assert_eq!(l.peek(), Some(&Token::Plus));
// since the lexer hasn't progressed, its span should be the same
assert_eq!(l.span(), 0..1);
```

Currently, the last assert fails and `span` gives `1..2` instead.

I guess the fix would be to use `prev_span` here instead of `span`-
https://github.com/ark0f/logos-iter/blob/8240fc7b136eb5e6233a2a9f890647c91f71d096/src/peekable.rs#L238

Would be happy to raise a PR if needed.

**Comment by ark0f** [comment]
Thanks for descriptive issue. Fixed and released
